# Data Collection

In [2]:
import pandas as pd
import numpy as np

## Overview of all sources

### 1 kaggle source 1

https://www.kaggle.com/datasets/adxie12/horoscopes/data

In [5]:
#globe
globe = pd.read_csv("/Users/isishassan/Documents/Ironhack/FinalProject/data/data sources/kaggle_source_1/globe_horoscopes_scraped.csv")

globe.head()

,sign,category,date,text
0,aries,general,december-18-2023,If you strive to impress people in positions o...
1,taurus,general,december-18-2023,"Don’t hold back today, make sure everyone know..."
2,gemini,general,december-18-2023,The planets warn you need to get to grips with...
3,cancer,general,december-18-2023,If there is something that has been bothering ...
4,leo,general,december-18-2023,A plan of some sort is not working out too wel...

Notes:
- columns: sign, category, date, text
- date format = monthname-date-year

In [145]:
#horoscopes1
horoscopes_1 = pd.read_csv("/Users/isishassan/Documents/Ironhack/FinalProject/data/kaggle_source_1/horoscopes_scraped_2025.csv")

horoscopes_1.head()

,sign,category,date,text
0,aries,general,20241111,"You're usually full of energy, Aries, but today you may not feel so vivacious. There's nothing to worry about. In fact, you may have the time to do some thinking about your personal life and what you expect to get out of your relationships. You might also want to think about how you intend to go about getting it! Perhaps some of your motivations have changed lately."
1,aries,general,20241112,"If you've been working toward manifesting extra money in your life, Aries, you will probably see it happen today. Copious physical and emotional energy gives your inner power of mind over matter a special impetus, and you might see the results you've wanted in finance and other matters. Professional interests should also be going well, as well as any personal projects. Keep up the good work!"
2,aries,general,20241113,"A group of people oriented toward artistic, spiritual, or humanitarian pursuits could meet virtually today to work on advancing their projects. Among them could be someone very special who might play a positive role in your life. As a result of this gathering you could find inspiration to move ahead with personal projects. In the evening, watch a romantic movie or talk to someone you’re attracted to!"
3,aries,general,20241114,You may find today that people are really attracted to you as a friend. This is because you're usually a good listener. You're open to other people's ideas and thoughts and can care easily. Consider noticing those around you to see if there isn't someone who could use an ear to listen to a problem. It may not take a lot to get someone talking.
4,aries,general,20241115,"If your partner acts quickly on his or her passions today, Aries, you will probably want to slow things down a bit. ""Nice and easy"" is the phrase of the day for you, so create an environment that will allow for more time in such circumstances. Let your partner know how you feel and what you'd like to see happen. No one is a mind reader. There's far less chance of any misunderstanding when there is open communication."

Notes:
- columns: sign, category, date, text
- dateformat: YYYYMMDD

### 2 kaggle: hindustan times

https://www.kaggle.com/datasets/prasad22/daily-horoscope-dataset

In [ ]:
hindu = pd.read_csv("/Users/isishassan/Documents/Ironhack/FinalProject/data/hindustan_times.csv", encoding='cp1252')

hindu.head()

Notes:
- columns: date, source, one column per sign
- to do: pivot signs to rows
- to do: remove info about "love focus", "lucky number", "lucky colour"
- date format: DD-MON-YY

### 3 kaggle: horoscope.com

https://www.kaggle.com/datasets/shahp7575/horoscopes

In [12]:
#horoscopes1
horoscopes_2 = pd.read_csv("/Users/isishassan/Documents/Ironhack/FinalProject/data/horoscope_com.csv")

horoscopes_2.head()

    sign category      date                                          horoscope
0  aries  general  20200617  There's a great day ahead of you, Aries. You'l...
1  aries  general  20200618  People will understand and appreciate your des...
2  aries  general  20200619  You are very interested in technological break...
3  aries  general  20200620  Stress from overwork could have you feeling we...
4  aries  general  20200621  This is a good day to stand up for yourself an...

Notes:
- columns: sign, category, date, horoscope
- date format: YYYYMMDD

## Data Standardisation

target:
- source
- sign (obj): aries, taurus, etc
- sign_id (numeric): 1 = aries, 2 = taurus, etc
- date (YYYY-MM-DD)
- horoscope

### kaggle source 1

In [147]:
#making a copy for safekeeping
globe_copy = globe.copy()

In [148]:
globe.head(2)

,sign,category,date,text
0,aries,general,december-18-2023,"If you strive to impress people in positions of power it won’t be long before you are on the way to the top as well. Let employers and senior colleagues know you are prepared to take on new responsibilities, then show them you’ve got what it takes."
1,taurus,general,december-18-2023,"Don’t hold back today, make sure everyone knows what you think and how you feel. Whether or not they agree with your outlook on life is less important than that they can see you are serious about what you will and will not put up with."

In [149]:
#dropping unneeded column
globe.drop("category",axis="columns",inplace=True)

In [150]:
#reformat date
globe["date"] = pd.to_datetime(globe["date"])

/var/folders/vl/4lkjvsxx3pv_m7ynmbqrfd780000gn/T/ipykernel_98122/4130839885.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  globe["date"] = pd.to_datetime(globe["date"])

In [151]:
globe["date"] = globe["date"].dt.strftime("%Y-%m-%d")

In [152]:
#renaming columns

globe.rename(columns={'text': 'horoscope'}, inplace=True)

In [153]:
#adding sign_id
globe["sign"].value_counts()

sign
aries             596
cancer            595
leo               595
virgo             595
libra             594
pisces            594
taurus            592
gemini            591
aquarius          586
scorpio           585
capricorn         582
sagittarius       567
if                  5
birthday            2
aquarius(jan.       1
capricorn(dec.      1
gemini(may          1
aries(march         1
pisces(feb.         1
aqurius             1
Name: count, dtype: int64

In [154]:
#needs cleanup first

globe["sign"] = globe["sign"].replace(
    ["aquarius(jan.","aqurius"],
    "aquarius"
)

In [155]:
globe["sign"] = globe["sign"].replace(
    ["capricorn(dec."],
    "capricorn"
)

In [156]:
globe["sign"] = globe["sign"].replace(
    ["gemini(may"],
    "gemini"
)

In [157]:
globe["sign"] = globe["sign"].replace(
    ["aries(march"],
    "aries"
)

In [158]:
globe["sign"] = globe["sign"].replace(
    ["pisces(feb."],
    "pisces"
)

In [159]:
#deleting rows
globe = globe[globe["sign"] != "if"]

In [160]:
globe = globe[globe["sign"] != "birthday"]

In [161]:
#dictionary with my sign_map so i can create id column
sign_map = {
    "aries": 1,
    "taurus": 2,
    "gemini": 3,
    "cancer": 4,
    "leo": 5,
    "virgo": 6,
    "libra": 7,
    "scorpio": 8,
    "sagittarius": 9,
    "capricorn": 10,
    "aquarius": 11,
    "pisces": 12
}

In [162]:
globe["sign_id"] = globe["sign"].map(sign_map)

In [163]:
globe.head()

,sign,date,horoscope,sign_id
0,aries,2023-12-18,"If you strive to impress people in positions of power it won’t be long before you are on the way to the top as well. Let employers and senior colleagues know you are prepared to take on new responsibilities, then show them you’ve got what it takes.",1
1,taurus,2023-12-18,"Don’t hold back today, make sure everyone knows what you think and how you feel. Whether or not they agree with your outlook on life is less important than that they can see you are serious about what you will and will not put up with.",2
2,gemini,2023-12-18,"The planets warn you need to get to grips with a problem that has been dogging you for quite some time. Partnership issues could be especially challenging over the next few days, so stay cool and look for solutions that everyone can agree on.",3
3,cancer,2023-12-18,"If there is something that has been bothering you then friends and family members will pick up on it quickly today. They know from past experience that your body language is a bit of a giveaway, and if they can find ways to help you they will.",4
4,leo,2023-12-18,"A plan of some sort is not working out too well, so stand back from what you are doing and try to work out where it fits in the wider picture. Should you push on with it or give up on it? Ultimately, only you can make that decision.",5

In [164]:
#adding source column
globe["source"] = "globe"

#### horoscopes_1

In [165]:
#making a copy for safekeeping
horoscopes_1_copy = horoscopes_1.copy()

In [166]:
#dropping unneeded column
horoscopes_1.drop("category",axis="columns",inplace=True)

In [167]:
#reformatting date
horoscopes_1["date"] = pd.to_datetime(horoscopes_1["date"].astype(str), format="%Y%m%d").dt.strftime("%Y-%m-%d")

In [168]:
horoscopes_1.head()

,sign,date,text
0,aries,2024-11-11,"You're usually full of energy, Aries, but today you may not feel so vivacious. There's nothing to worry about. In fact, you may have the time to do some thinking about your personal life and what you expect to get out of your relationships. You might also want to think about how you intend to go about getting it! Perhaps some of your motivations have changed lately."
1,aries,2024-11-12,"If you've been working toward manifesting extra money in your life, Aries, you will probably see it happen today. Copious physical and emotional energy gives your inner power of mind over matter a special impetus, and you might see the results you've wanted in finance and other matters. Professional interests should also be going well, as well as any personal projects. Keep up the good work!"
2,aries,2024-11-13,"A group of people oriented toward artistic, spiritual, or humanitarian pursuits could meet virtually today to work on advancing their projects. Among them could be someone very special who might play a positive role in your life. As a result of this gathering you could find inspiration to move ahead with personal projects. In the evening, watch a romantic movie or talk to someone you’re attracted to!"
3,aries,2024-11-14,You may find today that people are really attracted to you as a friend. This is because you're usually a good listener. You're open to other people's ideas and thoughts and can care easily. Consider noticing those around you to see if there isn't someone who could use an ear to listen to a problem. It may not take a lot to get someone talking.
4,aries,2024-11-15,"If your partner acts quickly on his or her passions today, Aries, you will probably want to slow things down a bit. ""Nice and easy"" is the phrase of the day for you, so create an environment that will allow for more time in such circumstances. Let your partner know how you feel and what you'd like to see happen. No one is a mind reader. There's far less chance of any misunderstanding when there is open communication."

In [169]:
#renaming column
horoscopes_1.rename(columns={'text': 'horoscope'}, inplace=True)

In [171]:
#checking if i need to clean up sign before adding sign_id

horoscopes_1["sign"].value_counts()

sign
aries          1831
taurus         1830
gemini         1830
cancer         1830
leo            1830
virgo          1830
libra          1830
scorpio        1830
sagittarius    1830
capricorn      1830
aquarius       1830
pisces         1830
Name: count, dtype: int64

In [172]:
#adding sign_id
horoscopes_1["sign_id"] = horoscopes_1["sign"].map(sign_map)

In [173]:
#adding source
horoscopes_1["source"] = "horoscope.com"

In [174]:
horoscopes_1.head()

,sign,date,horoscope,sign_id,source
0,aries,2024-11-11,"You're usually full of energy, Aries, but today you may not feel so vivacious. There's nothing to worry about. In fact, you may have the time to do some thinking about your personal life and what you expect to get out of your relationships. You might also want to think about how you intend to go about getting it! Perhaps some of your motivations have changed lately.",1,horoscope.com
1,aries,2024-11-12,"If you've been working toward manifesting extra money in your life, Aries, you will probably see it happen today. Copious physical and emotional energy gives your inner power of mind over matter a special impetus, and you might see the results you've wanted in finance and other matters. Professional interests should also be going well, as well as any personal projects. Keep up the good work!",1,horoscope.com
2,aries,2024-11-13,"A group of people oriented toward artistic, spiritual, or humanitarian pursuits could meet virtually today to work on advancing their projects. Among them could be someone very special who might play a positive role in your life. As a result of this gathering you could find inspiration to move ahead with personal projects. In the evening, watch a romantic movie or talk to someone you’re attracted to!",1,horoscope.com
3,aries,2024-11-14,You may find today that people are really attracted to you as a friend. This is because you're usually a good listener. You're open to other people's ideas and thoughts and can care easily. Consider noticing those around you to see if there isn't someone who could use an ear to listen to a problem. It may not take a lot to get someone talking.,1,horoscope.com
4,aries,2024-11-15,"If your partner acts quickly on his or her passions today, Aries, you will probably want to slow things down a bit. ""Nice and easy"" is the phrase of the day for you, so create an environment that will allow for more time in such circumstances. Let your partner know how you feel and what you'd like to see happen. No one is a mind reader. There's far less chance of any misunderstanding when there is open communication.",1,horoscope.com

In [175]:
print(horoscopes_1["date"].min())
print(horoscopes_1["date"].max())

2024-11-10
2025-11-10

### 2: hindustan times

In [176]:
hindu.head(2)

,Date,Source,Aries (March 21-April 20),Taurus (April 21-May 20),Gemini (May 21-Jun 21),Cancer (Jun 22-July 22),Leo (July 23-August 23),Virgo (August 24-September 23),Libra (September 24-October 23),Scorpio (October 24-November 22),Sagittarius (November 23-December 21),Capricorn (December 22-January 21),Aquarius (January 22-February 19),Pisces (February 20-March 20)
0,01-Jan-24,Hindustan Times,"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.\nLove Focus: Young couples must cater to each other’s mood to avoid turbulence in relationship.\n\nLucky Number: 3\n\nLucky Colour: Cream","Soaring expenses may become a cause for concern. Efforts will be required to keep good health. A big project may require total focus and energy. Chances of friends or relations coming and staying with you cannot be ruled out. A long drive may prove fatiguing for some. Prospects of owning property look bright, so go for it as this seems to be an auspicious day.\n\n\nLove Focus: Your romantic intentions may not be readily reciprocated, but persistence will pay!\n\nLucky Number: 2\n\nLucky Colour: Pink","A raise or an increment can be expected by some. Those feeling weak and listless of late may find their strength and energy returning. Finally, you may find things improving both on the personal and professional fronts. You are likely to devote your energies to make home a happy place to be in. Someone may be interested in taking you out of town. A new property acquired by you will start giving good monetary returns.\n\nLove Focus: Getting involved with someone on the romantic front cannot be ruled out, so rejoice!\n\nLucky Number:7\n\nLucky Colour: Green","Some of you are likely to follow in the footsteps of your more health-conscious friends and benefit. Despite rising expenses, you will be able to hold your own by judicious spending. Chance to display expertise will soon come to you on the professional front and you will manage to impress all. A child becomes a source of great pride. Those travelling out of town need to carry adequate money.\n\n\nLove Focus: A tiff with lover may affect the relationship.\n\nLucky Number: 5\n\nLucky Colour: Purple",Money lent to someone close appears as good as lost. Deteriorating health of someone close may cause worry. A gross miscalculation on the professional or business front threatens to turn things unfavourable. A family gathering can get you totally involved and prey on your time too. Road users need to exercise caution. Additions and alterations contemplated for the house may be given the green signal now.\n\nLove Focus: Your hopes of befriending someone from the opposite gender may be dashed.\n\nLucky Number: 2\n\nLucky Colour: Magenta,"Dreams of making it big on the financial front are likely to be realised sooner than expected. Those in the creative field may get a chance of a lifetime. Good health is assured, as you get motivated to shake a leg. Family will be supportive and prove a great help in whatever you are involved in. A pilgrimage may be planned by some. Buying property is very much on the cards for some.\n\n\nLove Focus: Romance flourishes as you draw closer to your loved one.\n\nLucky Number: 7\n\nLucky Colour: Saffron","Not being proactive on the professional front may impart a feeling to some that they have outlived their utility. Invest only if you are sure of the returns. You may be preparing for a celebration or a wedding in the family. You are likely to create a situation, just to meet lover! Some of you may set out on a vacation and enjoy yourself. If owning property is on your mind, a good bargain is waiting in the wings.\n\nLove Focus: Your romantic ideas are likely to provide much happiness to the beloved.\n\nLucky Number: 2\n\nLucky Colour: Silver","Those with money to invest may still be looking for some good options. If health is causing worry, don’t delay in getting yourself checked. Take professional help to get back into shape. You will need to be more responsive to the needs of spouse, if you want peace and harmony to prevail on the home front. Don’t pass up a chance to accompany someone on a trip, if you want to enjoy yourself. Emotional attachment with an ancestral property may not let you sell it.\n\n\nLove Focus: Turn on your charm on the romantic front and rejoice!\n\nLucky Number: 8\n\nLucky Colour: Yellow","Some of you are likely to start earning well or experience a windfall. You will need to keep up your exercise regimen to remain fit and energetic. Professionals will be able to raise their fees without loss of clients. Harmony is foreseen on the domestic front. Love life is likely to look up, as relationship grows stronger. Accompanying your near and dear ones on a journey promises lots of fun.\n\nLove Focus: An opportunity comes within your grasp on the romantic front, so don’t let it go!\n\nLucky Number:5\n\nLucky Colour: Golden","Businesspersons will be able to think up some good business strategies to maintain current profits. Your way with words is likely to convince all those opposed to your ideas on the work front. A family gathering is in the offing and promises much excitement. Love is in the air and you are likely to make the most of it today! Postponing a journey is possible, as you may not be in the mood for it.\n\n\nLove Focus: Luck is likely to favour those seeking love, so expect to enjoy a romance-filled day!\n\nLucky Number: 1\n\nLucky Colour: Maroon","You will need to be more careful on what you spend, as expenses are set to rise. Avoid excesses, if you value your health. You will need to hold your horses on a project at work, as some changes are expected. An important journey may have to be undertaken soon. Possibility of getting a property at a good price cannot be ruled out.\n\nLove Focus: Lack of confidence may mar your chances on the romantic front.\n\nLucky Number:6\n\nLucky Colour: Brown","It is best to start saving now, as it may become difficult later. Keeping a control over diet is important and will not prove difficult for you. An opportunity to impress those who matter on the professional front can materialise today. Resetting the house may become a priority with some homemakers. Those new to driving may need to remain extra vigilant today.\n\n\nLove Focus: Love is certainly in the air, but your recklessness in seeking it may put paid to your romantic aspirations.\n\nLucky Number: 22\n\nLucky Colour: Peach"
1,02-Jan-24,Hindustan Times,"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.\n\n\nLove Focus: Enhance matters of the heart with tenderness and deep understanding; plan meaningful moments with your partner.\n\nLucky Number: 17\n\nLucky Colour: Blue","Anticipate a steady wellness journey with consistent exercise and a balanced diet, ensuring lasting vitality. Despite some investments facing challenges, hold on; better times are on the horizon for financial prosperity. Confidence in professional ventures will pave the way for success; embrace opportunities with certainty. Enduring family bonds will bring comfort and joy. Embark on a thrilling journey to explore new horizons. Consider property investments with an eye on future gains; sow the seeds for lasting financial well-being.\n\n\nLove Focus: Love flourishes in every moment; create meaningful experiences to deepen your romantic connection.\n\nLucky Number: 22\n\nLucky Colour: Grey","Persist in your fitness journey, steady progress awaits. Tread carefully in financial matters, and consider conservative strategies for stability. Challenges at work may test you, but resilience is your key to a brighter professional future. Family bonds face trials, but your enduring love can weather the cosmic storm. Hold on major journeys for now as last-minute changes may invite more troubles. Creativity shines like a hidden gem, so explore it in various unexpected places. Proceed with cautious optimism in your real estate pursuits.\n\nLove Focus: Love’s path may be rocky, but with patience and understanding, celestial harmony can be restored.\n\n\nLucky Number: 4\n\nLucky Colour: Dark Yellow","The stars bring a refreshing breeze, filling you with vitality. Financial winds favor your sails; expect a prosperous cycle as your investments bear fruit. Professionally, you’re like a master painter, crafting your path to success with precision. Your family bonds are like a sturdy ship, weathering any storm that comes your way. Pack your bags for a beach reset with your group. The stars hint at positive returns in property investments, grounding your financial path.\n\nLove Focus: Anticipate a chapter of deep connection and romantic fulfillment.\n\nLucky Number: 8\n\nLucky Colour: Purple","Your health shines with vitality, encouraging you to maintain well-being and stay active. Financially, you are like a wise investor, making prudent decisions for your future. Professionally, opportunities are like ripe fruits waiting to be plucked. While family and romantic matters may pose challenges, patience and understanding are your guiding stars. Plan a getaway to break the routine and explore life’s surprises. Property investments may bring you future gains, like planting seeds in fertile soil.\n\n\nLove Focus: Love encounters a temporary pause; focus on personal growth to reignite the romantic cosmic spark.\n\nLucky Number: 6\n\nLucky Colour: Brown","Professionally, you are like a diligent scholar, dedicated to your path of success. Your health encourages you to maintain a balanced lifestyle, like a skilled tightrope walker gracefully navigating life’s challenges. Financially, you have the savvy of a shrewd investor, making decisions that secure your future. Family bonds remain strong. When it comes to travel, slow down a bit, and consider property investments that may yield future gains.\n\nLove Focus: Love’s path encounters a gentle breeze; navigate with measured enthusiasm for romantic balance.\n\nLucky Number: 1\n\nLucky Colour: White","Fine-tune your well-being routine. Explore new exercises or nutrition tweaks for sustained vitality. Consider diversified investments and strategic budgeting for stability. Inject creativity into your career path; seek innovative solutions and collaborations for professional growth. Strengthen family bonds through open communication and shared activities. Explore unique destinations, and let unexpected detours enhance your travel experience.\n\n\nLove Focus: Plan a surprise or express genuine emotions to deepen romantic ties.\n\nLucky Number: 2\n\nLucky Colour: Brown",Try exploring new fitness realms for sustained vitality. It’s a day to expect abundant returns and profits from past investments. Confront career challenges with a planned mindset. Reassess your path for professional growth. Domestic harmony can be only achieved through patience and open communication. Let the winds guide you to unexpected adventures.\n\nLove Focus: Plan a heartfelt gesture for a connection in your love story.\n\nLucky Number: 5\n\nLucky Colour: Dark Red,"Your well-being treads the middle path. Embrace balance; explore holistic practices. Small, consistent efforts pave the way for a vitality surge. Cultivate patience on the financial front and try considering diverse investments. A moderate approach now lays the foundation for future abundance. Seek growth in skill, not just position. Family bonds find stability. Nurture connections through shared experiences. Moderate efforts lead to lasting warmth on the home front. Travelers may be able to uncover hidden gems in a familiar place. Concerns related to a property may settle through an expert’s guidance.\n\n\nLove Focus: Embrace the pace; deeper connections evolve. A patient heart reaps the sweetest romantic rewards.\n\nLucky Number: 7\n\nLucky Colour: Peach","Your health calls for moderation and careful choices. Financially, exercise wisdom and prudence in your decisions. Professionally, adaptability and patience are your allies. Family bonds are your pillar of strength. While romance may require a bit more patience, travel holds exciting possibilities and property investments show potential. Seek excellence in various unexpected facets of your day, like uncovering hidden treasures.\n\nLove Focus: Love unfolds with a measured rhythm. Patience becomes the key to romantic fulfillment.\n\nLucky Number: 9\n\nLucky Colour: Maroon","Keep things balanced for your well-being. Take small steps consistently for lasting vitality. Money matters move steadily. Be patient, diversify your investments. Today’s moderation sets the stage for a secure financial future. Work-wise, take it steady. Focus on growing skills; unexpected career paths often reveal themselves with time. Family front may face challenges. Navigate with understanding and try to support as much as possible. Travel plans hit snags. Approach with caution, and learn from unexpected bumps along the way.\n\n\nLove Focus: Love hits a rough patch. Stay strong; tough times can lead to a more enduring and profound romance.\n\nLucky Number: 8\n\nLucky Colour: Cream","Your health shines brightly, like a beacon guiding you to stay active and embrace well-being. Financially, opportunities are knocking; make wise choices and secure your future. Professionally, you are on the path to success; seize the opportunities with confidence. Family matters may require some patience and understanding. Plan exciting journeys, explore property investments, and anticipate pleasant surprises sprinkled throughout your day.\n\nLove Focus: You can express your feelings to someone you like as love stars favour you today.\n\nLucky Number: 11\n\nLucky Colour: Silver"

In [177]:
#melt dataframe (instead of pivoting)

hindu_long = hindu.melt(
    id_vars=["Date", "Source"],
    var_name="sign",
    value_name="text"
)

In [178]:
hindu_long

,Date,Source,sign,text
0,01-Jan-24,Hindustan Times,Aries (March 21-April 20),"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.\nLove Focus: Young couples must cater to each other’s mood to avoid turbulence in relationship.\n\nLucky Number: 3\n\nLucky Colour: Cream"
1,02-Jan-24,Hindustan Times,Aries (March 21-April 20),"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.\n\n\nLove Focus: Enhance matters of the heart with tenderness and deep understanding; plan meaningful moments with your partner.\n\nLucky Number: 17\n\nLucky Colour: Blue"
2,03-Jan-24,Hindustan Times,Aries (March 21-April 20),"Maintaining an active life will do your health a whale of a good. You will have enough to spend and save too. Your willingness to take on even the toughest job at work will keep you on the right side of superiors. You may find spouse extra sensitive today, so steer clear! It may become difficult to avoid delays in a journey undertaken by you. Average returns from a property owned by you may not make you too happy.\n\n\nLove Focus: Positive indications from the one you secretly love are likely.\n\nLucky Number: 18\n\nLucky Colour: Brown"
3,04-Jan-24,Hindustan Times,Aries (March 21-April 20),"Today looks excellent across various aspects of your life. Your health is in top form, allowing you to seize the day fully. Financially, you can expect excellent stability and possible growth. Your professional life is high, presenting opportunities for a fantastic career. Family relations are thriving, and your romance is full of positivity. However, property matters may require careful consideration.\n\n\nLove Focus: Your love life is brimming with positivity.\n\nLucky Number: 22\n\nLucky Colour: Purple"
4,05-Jan-24,Hindustan Times,Aries (March 21-April 20),"It's time to look forward to the promising day ahead. Your health seems to be in good condition, providing a strong foundation for success. Money matters are favorable, with opportunities for growth and stability. While your professional and family lives may face basic challenges, you can manage them effectively. In romance, travel, and property-related matters, normalcy prevails, allowing for balanced decisions. In the other aspects of life, things are on a positive note, indicating a well-rounded and harmonious day for you.\n\n\nLove Focus: To keep your relationship balanced, romantic aspects may call for patience and conversation.\n\nLucky Number: 4\n\nLucky Colour: Orange"
...,...,...,...,...
2347,"July 11, 2024",Hindustan Times,Pisces (February 20-March 20),"Today, you will be in the mood to forgive minor mistakes at work. You will be able to raise the money to buy a luxury item. Yoga and meditation may hold special interest for you and provide immense benefits. A celebrity do or a celebration is likely to be attended and will prove lots of fun. You make a good start in something new on the academic front. Plans to visit a tourist destination may be put into effect now.\nLove Focus: An outing with a lover is on the anvil and will be most enjoyable.\nLucky Number: 6\nLucky Colour: Purple"
2348,"July 12, 2024",Hindustan Times,Pisces (February 20-March 20),NaN
2349,"Jan 1, 2025",Hindustan Times,Pisces (February 20-March 20),"Improving your sleep quality is as simple as reducing screen time before bed and embracing calming activities like journaling or meditation. On the financial front, rebuilding stability is possible through disciplined efforts and a patient approach—small steps lead to big results. Professionally, your goals seem within reach, so maintain focus and move forward steadily. Reconnecting with long-distance relatives can bring warmth and nostalgia; take the initiative to strengthen those bonds. Though travel plans may face delays, use the time to focus inward and nurture your inner peace.\nLove Focus: Love feels profound today. Share meaningful gestures to deepen your emotional bond.\nLucky Number: 22\nLucky Colour: Peach"
2350,"Jan 2, 2025",Hindustan Times,Pisces (February 20-March 20),"You’re feeling energized and motivated today, making it a great time to stay consistent with your wellness habits. Financial prospects appear promising; explore new avenues but ensure careful planning. Promising career opportunities await—stay proactive and aligned with your goals. At home, foster peace by avoiding past conflicts and embracing positivity. A short trip or spontaneous outing could lift your spirits. If you’ve been considering home upgrades or renovations, the timing is ideal to finalize pending tasks or kickstart new projects with confidence.\nLove Focus: Emotional bonds deepen as you spend meaningful time together. Let small gestures of care and understanding strengthen your connection.\nLucky Number: 11\nLucky Colour: Silver"
2351,"Jan 3, 2025",Hindustan Times,Pisces (February 20-March 20),"Fast food cravings may tempt you, but opting for wholesome alternatives could boost your health. Financially, adopting cost-cutting measures will likely stabilize your situation. At work, managing stress while balancing tasks can lead to better productivity. A hiking trip could refresh your mind while strengthening family bonds. Lounge access during travel provides a relaxing start to your journey. Property-related legal challenges might need expert assistance for smooth resolution.\nLove Focus: Subtle expressions of admiration from your partner can brighten your day—appreciate these moments.\nLucky Number: 9\nLucky Colour: Yellow"

In [179]:
#clean sign names up
hindu_long["sign"] = hindu_long["sign"].str.split("(").str[0].str.strip().str.lower()

In [180]:
#rename columns
hindu_long = hindu_long.rename(columns={"Date": "date", "Source": "source","text": "horoscope"})

In [181]:
#add sign_id
hindu_long["sign_id"] = hindu_long["sign"].map(sign_map)

In [182]:
hindu_long

,date,source,sign,horoscope,sign_id
0,01-Jan-24,Hindustan Times,aries,"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.\nLove Focus: Young couples must cater to each other’s mood to avoid turbulence in relationship.\n\nLucky Number: 3\n\nLucky Colour: Cream",1
1,02-Jan-24,Hindustan Times,aries,"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.\n\n\nLove Focus: Enhance matters of the heart with tenderness and deep understanding; plan meaningful moments with your partner.\n\nLucky Number: 17\n\nLucky Colour: Blue",1
2,03-Jan-24,Hindustan Times,aries,"Maintaining an active life will do your health a whale of a good. You will have enough to spend and save too. Your willingness to take on even the toughest job at work will keep you on the right side of superiors. You may find spouse extra sensitive today, so steer clear! It may become difficult to avoid delays in a journey undertaken by you. Average returns from a property owned by you may not make you too happy.\n\n\nLove Focus: Positive indications from the one you secretly love are likely.\n\nLucky Number: 18\n\nLucky Colour: Brown",1
3,04-Jan-24,Hindustan Times,aries,"Today looks excellent across various aspects of your life. Your health is in top form, allowing you to seize the day fully. Financially, you can expect excellent stability and possible growth. Your professional life is high, presenting opportunities for a fantastic career. Family relations are thriving, and your romance is full of positivity. However, property matters may require careful consideration.\n\n\nLove Focus: Your love life is brimming with positivity.\n\nLucky Number: 22\n\nLucky Colour: Purple",1
4,05-Jan-24,Hindustan Times,aries,"It's time to look forward to the promising day ahead. Your health seems to be in good condition, providing a strong foundation for success. Money matters are favorable, with opportunities for growth and stability. While your professional and family lives may face basic challenges, you can manage them effectively. In romance, travel, and property-related matters, normalcy prevails, allowing for balanced decisions. In the other aspects of life, things are on a positive note, indicating a well-rounded and harmonious day for you.\n\n\nLove Focus: To keep your relationship balanced, romantic aspects may call for patience and conversation.\n\nLucky Number: 4\n\nLucky Colour: Orange",1
...,...,...,...,...,...
2347,"July 11, 2024",Hindustan Times,pisces,"Today, you will be in the mood to forgive minor mistakes at work. You will be able to raise the money to buy a luxury item. Yoga and meditation may hold special interest for you and provide immense benefits. A celebrity do or a celebration is likely to be attended and will prove lots of fun. You make a good start in something new on the academic front. Plans to visit a tourist destination may be put into effect now.\nLove Focus: An outing with a lover is on the anvil and will be most enjoyable.\nLucky Number: 6\nLucky Colour: Purple",12
2348,"July 12, 2024",Hindustan Times,pisces,NaN,12
2349,"Jan 1, 2025",Hindustan Times,pisces,"Improving your sleep quality is as simple as reducing screen time before bed and embracing calming activities like journaling or meditation. On the financial front, rebuilding stability is possible through disciplined efforts and a patient approach—small steps lead to big results. Professionally, your goals seem within reach, so maintain focus and move forward steadily. Reconnecting with long-distance relatives can bring warmth and nostalgia; take the initiative to strengthen those bonds. Though travel plans may face delays, use the time to focus inward and nurture your inner peace.\nLove Focus: Love feels profound today. Share meaningful gestures to deepen your emotional bond.\nLucky Number: 22\nLucky Colour: Peach",12
2350,"Jan 2, 2025",Hindustan Times,pisces,"You’re feeling energized and motivated today, making it a great time to stay consistent with your wellness habits. Financial prospects appear promising; explore new avenues but ensure careful planning. Promising career opportunities await—stay proactive and aligned with your goals. At home, foster peace by avoiding past conflicts and embracing positivity. A short trip or spontaneous outing could lift your spirits. If you’ve been considering home upgrades or renovations, the timing is ideal to finalize pending tasks or kickstart new projects with confidence.\nLove Focus: Emotional bonds deepen as you spend meaningful time together. Let small gestures of care and understanding strengthen your connection.\nLucky Number: 11\nLucky Colour: Silver",12
2351,"Jan 3, 2025",Hindustan Times,pisces,"Fast food cravings may tempt you, but opting for wholesome alternatives could boost your health. Financially, adopting cost-cutting measures will likely stabilize your situation. At work, managing stress while balancing tasks can lead to better productivity. A hiking trip could refresh your mind while strengthening family bonds. Lounge access during travel provides a relaxing start to your journey. Property-related legal challenges might need expert assistance for smooth resolution.\nLove Focus: Subtle expressions of admiration from your partner can brighten your day—appreciate these moments.\nLucky Number: 9\nLucky Colour: Yellow",12

In [183]:
#reformat date
hindu_long["date"] = pd.to_datetime(hindu_long["date"]).dt.strftime("%Y-%m-%d")

/var/folders/vl/4lkjvsxx3pv_m7ynmbqrfd780000gn/T/ipykernel_98122/4008854798.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hindu_long["date"] = pd.to_datetime(hindu_long["date"]).dt.strftime("%Y-%m-%d")

In [184]:
hindu_long.head()

,date,source,sign,horoscope,sign_id
0,2024-01-01,Hindustan Times,aries,"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.\nLove Focus: Young couples must cater to each other’s mood to avoid turbulence in relationship.\n\nLucky Number: 3\n\nLucky Colour: Cream",1
1,2024-01-02,Hindustan Times,aries,"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.\n\n\nLove Focus: Enhance matters of the heart with tenderness and deep understanding; plan meaningful moments with your partner.\n\nLucky Number: 17\n\nLucky Colour: Blue",1
2,2024-01-03,Hindustan Times,aries,"Maintaining an active life will do your health a whale of a good. You will have enough to spend and save too. Your willingness to take on even the toughest job at work will keep you on the right side of superiors. You may find spouse extra sensitive today, so steer clear! It may become difficult to avoid delays in a journey undertaken by you. Average returns from a property owned by you may not make you too happy.\n\n\nLove Focus: Positive indications from the one you secretly love are likely.\n\nLucky Number: 18\n\nLucky Colour: Brown",1
3,2024-01-04,Hindustan Times,aries,"Today looks excellent across various aspects of your life. Your health is in top form, allowing you to seize the day fully. Financially, you can expect excellent stability and possible growth. Your professional life is high, presenting opportunities for a fantastic career. Family relations are thriving, and your romance is full of positivity. However, property matters may require careful consideration.\n\n\nLove Focus: Your love life is brimming with positivity.\n\nLucky Number: 22\n\nLucky Colour: Purple",1
4,2024-01-05,Hindustan Times,aries,"It's time to look forward to the promising day ahead. Your health seems to be in good condition, providing a strong foundation for success. Money matters are favorable, with opportunities for growth and stability. While your professional and family lives may face basic challenges, you can manage them effectively. In romance, travel, and property-related matters, normalcy prevails, allowing for balanced decisions. In the other aspects of life, things are on a positive note, indicating a well-rounded and harmonious day for you.\n\n\nLove Focus: To keep your relationship balanced, romantic aspects may call for patience and conversation.\n\nLucky Number: 4\n\nLucky Colour: Orange",1

### 3 horoscopes.com

In [185]:
horoscopes_2_copy = horoscopes_2.copy()

In [186]:
horoscopes_2.head()

,sign,date,horoscope,sign_id,source
0,aries,2020-06-17,"There's a great day ahead of you, Aries. You'll be blessed with the ability to solve problems, and others will come looking for you today. You'll listen, understand, and express empathy. You'll be wise enough to find solutions to any issues they present to you. After a day like this, you might ask yourself if you shouldn't work as a therapist.",1,horoscope.com
1,aries,2020-06-18,"People will understand and appreciate your desire to stand out from the crowd today, Aries. This isn't a sign of arrogance on your part. It's just that you're particularly perceptive right now and people need your good advice. Since you're ready to step into the spotlight and shine like the stars that are giving you all this wonderful energy, go for it. You'd kick yourself if you let this opportunity pass.",1,horoscope.com
2,aries,2020-06-19,"You are very interested in technological breakthroughs and innovation, Aries, especially if it has some benefit for individuals. Since you also concern yourself with social issues and subjects like psychology and spiritual therapies, you realize the importance of progress in these areas for the future. You also wonder where you fit in.",1,horoscope.com
3,aries,2020-06-20,"Stress from overwork could have you feeling weaker than usual. You might be tempted to stay at home, get some rest, and recoup your energies. Do this if you can, Aries. Otherwise, you may not be able to give your project the concentration it needs, and therefore may not accomplish as much as you think you should. If you feel you can't stay home, try to work alone so you won't be distracted.",1,horoscope.com
4,aries,2020-06-21,"This is a good day to stand up for yourself and make it known that you aren't a pushover, Aries. Use the powerful energy of the day to follow through on projects that may have lost momentum. Pick up the reins and take control of the direction of your life. Feel free to be more aggressive than you normally would. Show others your incredible worth.",1,horoscope.com

In [107]:
#reformat date

horoscopes_2["date"] = pd.to_datetime(horoscopes_2["date"].astype(str), format="%Y%m%d").dt.strftime("%Y-%m-%d")

In [ ]:
#bad data: sign

horoscopes_2["sign"].value_counts()

#A: none, I can proceed to sign_id but want to double check it's a different time period than horoscopes_1

sign
taurus         1830
gemini         1830
cancer         1830
leo            1830
virgo          1830
libra          1830
scorpio        1830
sagittarius    1830
capricorn      1830
aquarius       1830
pisces         1830
aries          1829
Name: count, dtype: int64

In [113]:
print(horoscopes_2["date"].min())
print(horoscopes_2["date"].max())

2020-06-16
2021-06-16

In [114]:
horoscopes_2.head()

    sign        date                                          horoscope
0  aries  2020-06-17  There's a great day ahead of you, Aries. You'l...
1  aries  2020-06-18  People will understand and appreciate your des...
2  aries  2020-06-19  You are very interested in technological break...
3  aries  2020-06-20  Stress from overwork could have you feeling we...
4  aries  2020-06-21  This is a good day to stand up for yourself an...

In [115]:
#adding sign_id

horoscopes_2["sign_id"] = horoscopes_2["sign"].map(sign_map)

In [116]:
#adding source

horoscopes_2["source"] = "horoscope.com"

In [119]:
horoscopes_2.head()

,sign,date,horoscope,sign_id,source
0,aries,2020-06-17,"There's a great day ahead of you, Aries. You'l...",1,horoscope.com
1,aries,2020-06-18,People will understand and appreciate your des...,1,horoscope.com
2,aries,2020-06-19,You are very interested in technological break...,1,horoscope.com
3,aries,2020-06-20,Stress from overwork could have you feeling we...,1,horoscope.com
4,aries,2020-06-21,This is a good day to stand up for yourself an...,1,horoscope.com

# Combine

In [188]:
combined = pd.concat([globe, hindu_long, horoscopes_1, horoscopes_2], ignore_index=True)

In [189]:
combined.shape

(53350, 5)

## Data Cleaning

- hindustan times: remove everything starting with "love focus" (incl)
- replace all sign names with [Sign Name]

In [128]:
#replace sign names

combined["horoscope"] = combined["horoscope"].replace(
    ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagitarrius","Capricorn","Aquarius","Pisces"],
    "[Sign Name]"
)

In [133]:
import pandas as pd

# Show full column content
pd.set_option('display.max_colwidth', None)

In [199]:
filtered_df = combined[combined['horoscope'].str.contains('Aries', case=False, na=False)]

filtered_df

,sign,date,horoscope,sign_id,source
819,aries,2024-03-01,"If you are the sort of Aries who enjoys the finer things in life you will be getting plenty of them over the next few days. A sun-Jupiter link will boost your money-making potential, though you will no doubt spend it as quickly as you get it!",1,globe
1052,aries,2024-03-22,"Mars, your ruler, moves into the most sensitive area of your chart today, so even if you are the sort of Aries who shrugs off criticism easily you may find that other people’s negative comments wind you up more than usual. Bark back but don’t bite!",1,globe
1164,sagittarius,2024-04-02,If this isn’t a fun time for you then you must be doing something very wrong. The sun in Aries should be motivating you to give of your best at every opportunity – and if that isn’t happening then maybe you need to focus on more challenging goals.,9,globe
1208,aries,2024-04-06,"Your recent run of good luck is destined to continue, starting this weekend with Venus in your sign linking up with power planet Pluto. Authority figures will be watching you closely and will love what they see. You’ve got that Aries star quality.",1,globe
1229,sagittarius,2024-04-08,"Don’t hesitate to put your own interests first today and don’t stop putting them first until you have reached the desired outcome. Today’s eclipse in your fellow fire sign of Aries makes this the most dynamic time of the year for you, so do something with it!",9,globe
...,...,...,...,...,...
52732,pisces,2020-10-08,"You are a natural nurturer, and no matter how much we tell you to nurture yourself you will always have a need to nurture others. Try to combine the two wherever possible. In fact, the planetary energy at play gives you increased perception, and you are intuitively able to sense your boundaries. You may find you wake up early in the morning during the current transit. It's a great time to take a walk and give yourself some personal time - and the dog might love it, too!",12,horoscope.com
52771,pisces,2020-11-16,"Be on the lookout for issues that flair up around friends and family these days. You may be open to new ideas and new ways of thinking, but don't let this ""open-mindedness"" get you into trouble. The aspect of the day will typically bring up some boundary issues. You have the right to say ""no"" when a boundary is being crossed. And you are the one who sets the boundaries! Practice yoga or meditation to stay on top of your best interests.",12,horoscope.com
52920,pisces,2021-04-14,"You are no stranger to change, but it may take some reining in of your personal power in order to direct your ability to change constructively. Imagine you are both your own father and your own mother (depending on your age, this will be easier or harder to do), and create your boundaries - your actions and language, your limits in relationships, your requirements on the job - and you are also in charge of nurturing yourself with the food, the rest, the exercise, the affection you need to survive. Don't forget to give yourself a lot of positive reinforcement!",12,horoscope.com
53005,pisces,2020-07-07,"It's a high-energy, extroverted year! Keep some personal pleasure in your equation, even if spending time with others is your primary source of happiness. Just don't let it take over your life. A family or home concern may take all your energy in October, and it will be worth it. Don't be frustrated in November if people aren't always there for you. Respect everyone's boundaries, especially your own, and don't take everything personally. Work may heat up in April. Stay grounded and meet the challenge. It's a smooth, comforting end of the year with more love than you might have dreamed!",12,horoscope.com
53020,pisces,2020-07-22,"Feelings run deep and strong this year, and you may prefer to keep them to yourself. Secrecy and mystery may appeal to you, but simply respecting privacy may work just as well. The first month you'll be conspicuous, so don't bother hiding how lucky and attractive you naturally are. In the autumn you may need to be a diplomat with friends or family. Be sensitive to all sides, respecting privacy and boundaries, and achieve satisfaction everywhere. After a brief spell in the limelight in April, return to your cozy emotional cave and lap up endless love, comfort, and affection till year's end!",12,horoscope.com

In [231]:
combined['horoscope'] = combined['horoscope'].replace(
    to_replace=r'Aries|Taurus|Gemini|Cancer|Leo|Virgo|Libra|Scorpio|Sagittarius|Capricorn|Aquarius|Pisces',  # regex pattern matching either word
    value='[Sign Name]',
    regex=True
)

In [232]:
#cutting out unnecessary stuff from hindustan times

#filtered_df = combined['source'] == "Hindustan Times"

filtered_df = combined[combined['source'] == 'Hindustan Times']
display(filtered_df)

,sign,date,horoscope,sign_id,source
7078,aries,2024-01-01,"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.",1,Hindustan Times
7079,aries,2024-01-02,"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.",1,Hindustan Times
7080,aries,2024-01-03,"Maintaining an active life will do your health a whale of a good. You will have enough to spend and save too. Your willingness to take on even the toughest job at work will keep you on the right side of superiors. You may find spouse extra sensitive today, so steer clear! It may become difficult to avoid delays in a journey undertaken by you. Average returns from a property owned by you may not make you too happy.",1,Hindustan Times
7081,aries,2024-01-04,"Today looks excellent across various aspects of your life. Your health is in top form, allowing you to seize the day fully. Financially, you can expect excellent stability and possible growth. Your professional life is high, presenting opportunities for a fantastic career. Family relations are thriving, and your romance is full of positivity. However, property matters may require careful consideration.",1,Hindustan Times
7082,aries,2024-01-05,"It's time to look forward to the promising day ahead. Your health seems to be in good condition, providing a strong foundation for success. Money matters are favorable, with opportunities for growth and stability. While your professional and family lives may face basic challenges, you can manage them effectively. In romance, travel, and property-related matters, normalcy prevails, allowing for balanced decisions. In the other aspects of life, things are on a positive note, indicating a well-rounded and harmonious day for you.",1,Hindustan Times
...,...,...,...,...,...
9425,pisces,2024-07-11,"Today, you will be in the mood to forgive minor mistakes at work. You will be able to raise the money to buy a luxury item. Yoga and meditation may hold special interest for you and provide immense benefits. A celebrity do or a celebration is likely to be attended and will prove lots of fun. You make a good start in something new on the academic front. Plans to visit a tourist destination may be put into effect now.",12,Hindustan Times
9426,pisces,2024-07-12,NaN,12,Hindustan Times
9427,pisces,2025-01-01,"Improving your sleep quality is as simple as reducing screen time before bed and embracing calming activities like journaling or meditation. On the financial front, rebuilding stability is possible through disciplined efforts and a patient approach—small steps lead to big results. Professionally, your goals seem within reach, so maintain focus and move forward steadily. Reconnecting with long-distance relatives can bring warmth and nostalgia; take the initiative to strengthen those bonds. Though travel plans may face delays, use the time to focus inward and nurture your inner peace.",12,Hindustan Times
9428,pisces,2025-01-02,"You’re feeling energized and motivated today, making it a great time to stay consistent with your wellness habits. Financial prospects appear promising; explore new avenues but ensure careful planning. Promising career opportunities await—stay proactive and aligned with your goals. At home, foster peace by avoiding past conflicts and embracing positivity. A short trip or spontaneous outing could lift your spirits. If you’ve been considering home upgrades or renovations, the timing is ideal to finalize pending tasks or kickstart new projects with confidence.",12,Hindustan Times
9429,pisces,2025-01-03,"Fast food cravings may tempt you, but opting for wholesome alternatives could boost your health. Financially, adopting cost-cutting measures will likely stabilize your situation. At work, managing stress while balancing tasks can lead to better productivity. A hiking trip could refresh your mind while strengthening family bonds. Lounge access during travel provides a relaxing start to your journey. Property-related legal challenges might need expert assistance for smooth resolution.",12,Hindustan Times

In [233]:
#removing everything related to lucky number and colour
combined['horoscope'] = combined['horoscope'].str.split('\n', n=1).str[0]

In [234]:
#checking if it worked:
filtered_df = combined[combined['source'] == 'Hindustan Times']
display(filtered_df)

,sign,date,horoscope,sign_id,source
7078,aries,2024-01-01,"You will need to remain consistent in your exercise routine, if fitness is your aim, irregularity will just not do. You may have to keep your feet firmly on the ground to stem wasteful expenditure. Professionals may need to boost their business. A forthcoming family event is likely to raise your spirits. Remain alert on the road while driving. A property matter assumes importance.",1,Hindustan Times
7079,aries,2024-01-02,"A unique blend of challenges and opportunities are the highlights of the day. Health and financial hurdles may seem daunting, but they are stepping stones for personal growth. On the bright side, your professional endeavors will flourish, shining with remarkable success. Your family bonds are a precious treasure, and love will thrive in your personal life. Plan an exhilarating journey, explore property investments, and expect delightful surprises sprinkled throughout your day.",1,Hindustan Times
7080,aries,2024-01-03,"Maintaining an active life will do your health a whale of a good. You will have enough to spend and save too. Your willingness to take on even the toughest job at work will keep you on the right side of superiors. You may find spouse extra sensitive today, so steer clear! It may become difficult to avoid delays in a journey undertaken by you. Average returns from a property owned by you may not make you too happy.",1,Hindustan Times
7081,aries,2024-01-04,"Today looks excellent across various aspects of your life. Your health is in top form, allowing you to seize the day fully. Financially, you can expect excellent stability and possible growth. Your professional life is high, presenting opportunities for a fantastic career. Family relations are thriving, and your romance is full of positivity. However, property matters may require careful consideration.",1,Hindustan Times
7082,aries,2024-01-05,"It's time to look forward to the promising day ahead. Your health seems to be in good condition, providing a strong foundation for success. Money matters are favorable, with opportunities for growth and stability. While your professional and family lives may face basic challenges, you can manage them effectively. In romance, travel, and property-related matters, normalcy prevails, allowing for balanced decisions. In the other aspects of life, things are on a positive note, indicating a well-rounded and harmonious day for you.",1,Hindustan Times
...,...,...,...,...,...
9425,pisces,2024-07-11,"Today, you will be in the mood to forgive minor mistakes at work. You will be able to raise the money to buy a luxury item. Yoga and meditation may hold special interest for you and provide immense benefits. A celebrity do or a celebration is likely to be attended and will prove lots of fun. You make a good start in something new on the academic front. Plans to visit a tourist destination may be put into effect now.",12,Hindustan Times
9426,pisces,2024-07-12,NaN,12,Hindustan Times
9427,pisces,2025-01-01,"Improving your sleep quality is as simple as reducing screen time before bed and embracing calming activities like journaling or meditation. On the financial front, rebuilding stability is possible through disciplined efforts and a patient approach—small steps lead to big results. Professionally, your goals seem within reach, so maintain focus and move forward steadily. Reconnecting with long-distance relatives can bring warmth and nostalgia; take the initiative to strengthen those bonds. Though travel plans may face delays, use the time to focus inward and nurture your inner peace.",12,Hindustan Times
9428,pisces,2025-01-02,"You’re feeling energized and motivated today, making it a great time to stay consistent with your wellness habits. Financial prospects appear promising; explore new avenues but ensure careful planning. Promising career opportunities await—stay proactive and aligned with your goals. At home, foster peace by avoiding past conflicts and embracing positivity. A short trip or spontaneous outing could lift your spirits. If you’ve been considering home upgrades or renovations, the timing is ideal to finalize pending tasks or kickstart new projects with confidence.",12,Hindustan Times
9429,pisces,2025-01-03,"Fast food cravings may tempt you, but opting for wholesome alternatives could boost your health. Financially, adopting cost-cutting measures will likely stabilize your situation. At work, managing stress while balancing tasks can lead to better productivity. A hiking trip could refresh your mind while strengthening family bonds. Lounge access during travel provides a relaxing start to your journey. Property-related legal challenges might need expert assistance for smooth resolution.",12,Hindustan Times

In [235]:
#duplicates

combined.duplicated().sum()

np.int64(1)

In [236]:
#dropping my dupe
combined_clean = pd.DataFrame.drop_duplicates(combined)

# Storing my cleaned dataset

In [237]:
combined_clean_copy = combined_clean.copy()

In [238]:
#saving to a csv
combined_clean.to_csv('combined_cleaned.csv', index=False)

In [239]:
#saving to pickle, so I can import in new jupyter notebook

combined_clean.to_pickle('combined_cleaned.pkl')